name: Build, Test, Check, Package

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build
      run: |
            ./syncComposeSharedSources.sh
            ./gradlew --no-daemon compileReleaseSources assembleDist

    - name: Test
      run: ./gradlew --no-daemon test

    - name: Lint
      run: ./gradlew --no-daemon :wordle-compose-android:lintRelease -x lint

    - name: Publish Test Reports
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'

    - name: Dist
      env:
        PLAYSTORE_SECRET_PASSPHRASE: ${{ secrets.PLAYSTORE_SECRET_PASSPHRASE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      run: |
            playstore_file=$(_ci/decrypt_keystore.sh)
            ./gradlew --no-daemon \
              -Pci=true \
              -Pplaystore.keystore.file="$playstore_file" \
              -Pplaystore.keystore.password="$KEYSTORE_PASSWORD" \
              -Pplaystore.keystore.key_password="$KEYSTORE_KEY_PASSWORD" \
              :wordle-compose-desktop:assembleDist \
              :wordle-compose-mosaic:assembleDist \
              :wordle-compose-android:assembleRelease \
              -x lint
