name: Build, Test, Check, Package

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      run: |
            ./syncComposeSharedSources.sh
            ./gradlew --no-daemon compileReleaseSources

    - name: Test
      run: ./gradlew --no-daemon test -x testDebug

    - name: Lint
      run: ./gradlew --no-daemon :wordle-compose-android:lintRelease -x lint

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.26
      if: failure()
      with:
        files: ./**/build/test-results/test/TEST-*.xml

    - name: Dist
      env:
        PLAYSTORE_SECRET_PASSPHRASE: ${{ secrets.PLAYSTORE_SECRET_PASSPHRASE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      run: |
            playstore_file=$(_ci/decrypt_keystore.sh)
            ./gradlew --no-daemon \
              -Pci=true \
              -Pplaystore.keystore.file="$playstore_file" \
              -Pplaystore.keystore.password="$KEYSTORE_PASSWORD" \
              -Pplaystore.keystore.key_password="$KEYSTORE_KEY_PASSWORD" \
              :wordle-compose-desktop:assembleDist \
              :wordle-compose-android:assembleRelease \
              -x lint

    - name: Archive app APK
      uses: actions/upload-artifact@v2
      with:
        name: wordle-compose-android-release.apk
        path: wordle-compose-android/build/outputs/apk/release/wordle-compose-android-release.apk
      if: github.ref == 'refs/heads/master'
