name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      run: ./gradlew --no-daemon assemble

    - name: Test
      run: ./gradlew --no-daemon test

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.26
      if: failure()
      with:
        files: ./**/build/test-results/test/TEST-*.xml

    - name: Dist
      run: ./gradlew --no-daemon assembleDist

